[package]
name = "ttx-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
ttkmd-if = { git = "https://github.com/tenstorrent/luwen/", rev = "a5d932ab6021f4302f28e6917440090778335a5b" }
luwen-core = { git = "https://github.com/tenstorrent/luwen/", rev = "a5d932ab6021f4302f28e6917440090778335a5b" }
tensix-builder = { path = "./tensix-builder" }
macros = { path = "./macros" }

relocate = { path = "./relocate" }

tracing = { workspace = true }

goblin = { workspace = true }
thiserror = "2.0.9"

postcard = { workspace = true }
serde = { workspace = true, features = ["std"] }

num-derive = "0.4.2"
num-traits = "0.2.19"

tempfile = "3.20.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ctor = "0.4.2"

[workspace]
members = [ "app/ggml-rs","relocate", "runtime/runtime-executor", "runtime/runtime-shared"]

[workspace.dependencies]
postcard = { version = "1.1.1", features = [
    "postcard-derive",
    "experimental-derive",
] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
goblin = "0.8.2"
tracing = "0.1.41"
